# Generated by Django 4.2.10 on 2025-10-16 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['project', 'status'], name='projects_un_project_1cf609_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_number'], name='projects_un_unit_nu_31b7be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('project', 'unit_number')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'status'], name='projects_pr_company_48dbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code'], name='projects_pr_code_80abae_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['city', 'state'], name='projects_pr_city_d1254d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='projects_pr_created_775fe7_idx'),
        ),
    ]
