# Generated by Django 4.2.10 on 2025-10-16 16:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('glb_code', models.CharField(blank=True, max_length=255)),
                ('stage_number', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('housing_typology', models.CharField(blank=True, help_text='e.g., NOVIS, VIS', max_length=100)),
                ('separation', models.DecimalField(decimal_places=2, default=0, help_text='Separation percentage', max_digits=5)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, help_text='Down payment percentage', max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage', max_digits=5)),
                ('projected_increase', models.DecimalField(decimal_places=2, default=0, help_text='Projected price increase percentage', max_digits=5)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('media_items', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company')),
            ],
            options={
                'ordering': ['project', 'stage_number', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='project',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='allow_quote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='background_color',
            field=models.CharField(blank=True, help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='crm',
            field=models.CharField(choices=[('monday', 'Monday.com'), ('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='crm_config',
            field=models.JSONField(blank=True, default=dict, help_text='CRM configuration (API keys, board IDs, etc)'),
        ),
        migrations.AddField(
            model_name='project',
            name='crm_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='economic_profiles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='measure_unit',
            field=models.CharField(default='m²', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='media_items',
            field=models.JSONField(blank=True, default=list, help_text='Array of media items with type, reference, and url'),
        ),
        migrations.AddField(
            model_name='project',
            name='orbit_view_amenities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='orbit_view_project',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='orbit_views_string',
            field=models.CharField(blank=True, help_text='Legacy orbit views reference', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='score_weights',
            field=models.JSONField(blank=True, default=dict, help_text='Weights for scoring leads'),
        ),
        migrations.AddField(
            model_name='project',
            name='show_prices',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status_colors',
            field=models.JSONField(blank=True, default=dict, help_text='Colors for different unit statuses'),
        ),
        migrations.AddField(
            model_name='unit',
            name='balcony_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='unit',
            name='balcony_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='build_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='unit',
            name='complementary_unit',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='unit',
            name='complementary_units',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='unit',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='glb_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='unit',
            name='mezzanine_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='price_type',
            field=models.CharField(choices=[('fixedPrice', 'Fixed Price'), ('smlvPrice', 'SMLV Price')], default='fixedPrice', max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='private_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='terrace_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='unit',
            name='terrace_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='terrace_private_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='unit',
            name='typology_slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.CharField(default='CO', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(default='COP', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='currency',
            field=models.CharField(default='COP', max_length=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('blocked', 'Blocked'), ('optioned', 'Optioned'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(blank=True, help_text='e.g., Studio, 1BR, 2BR, Penthouse', max_length=100),
        ),
        migrations.CreateModel(
            name='Typology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('glb_code', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bedrooms', models.CharField(blank=True, max_length=10)),
                ('bathrooms', models.CharField(blank=True, max_length=10)),
                ('target_frame', models.CharField(blank=True, max_length=10)),
                ('media_items', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typologies', to='projects.stage')),
            ],
            options={
                'ordering': ['stage', 'code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project'),
        ),
        migrations.CreateModel(
            name='OrbitView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('orbit_type', models.CharField(choices=[('project', 'Project'), ('amenities', 'Amenities'), ('unit-types', 'Unit Types'), ('block', 'Block')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('images_folder', models.CharField(blank=True, max_length=255)),
                ('images_extension', models.CharField(default='webp', max_length=10)),
                ('num_images', models.IntegerField(default=0)),
                ('glb_file', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orbit_views', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'orbit_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('glb_code', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_frame', models.CharField(blank=True, max_length=10)),
                ('price_list', models.CharField(blank=True, max_length=255)),
                ('smlv_price', models.DecimalField(decimal_places=2, default=0, help_text='SMLV price', max_digits=12)),
                ('media_items', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.stage')),
            ],
            options={
                'ordering': ['stage', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent_type', models.CharField(choices=[('project', 'Project'), ('block', 'Block')], max_length=10)),
                ('parent_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('glb_code', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('media_items', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company')),
            ],
            options={
                'ordering': ['parent_type', 'parent_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='projects.block'),
        ),
        migrations.AddField(
            model_name='unit',
            name='typology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='projects.typology'),
        ),
        migrations.AddIndex(
            model_name='typology',
            index=models.Index(fields=['stage', 'code'], name='projects_ty_stage_i_eaeb59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typology',
            unique_together={('stage', 'slug')},
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['project', 'stage_number'], name='projects_st_project_9ff1e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('project', 'slug')},
        ),
        migrations.AddIndex(
            model_name='orbitview',
            index=models.Index(fields=['project', 'orbit_type'], name='projects_or_project_66e97a_idx'),
        ),
        migrations.AddIndex(
            model_name='orbitview',
            index=models.Index(fields=['slug'], name='projects_or_slug_1a93dc_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['stage', 'code'], name='projects_bl_stage_i_f9f530_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('stage', 'slug')},
        ),
        migrations.AddIndex(
            model_name='amenity',
            index=models.Index(fields=['parent_type', 'parent_id'], name='projects_am_parent__900430_idx'),
        ),
    ]
