# Generated by Django 4.2.10 on 2025-10-16 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID or VAT number', max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_users', models.IntegerField(default=5)),
                ('max_projects', models.IntegerField(default=10)),
                ('max_leads', models.IntegerField(default=1000)),
                ('max_storage_gb', models.IntegerField(default=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('features', models.JSONField(blank=True, default=dict, help_text='Enabled features for this company')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='companies_c_slug_45751b_idx'), models.Index(fields=['status'], name='companies_c_status_2407e4_idx'), models.Index(fields=['plan'], name='companies_c_plan_30710e_idx')],
            },
        ),
    ]
