# Generated by Django 4.2.10 on 2025-10-16 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Nombre de la tarea. Ej: 'Recordatorios de Follow-ups'", max_length=255)),
                ('description', models.TextField(help_text="Qué hace esta tarea. Ej: 'Envía emails a vendedores con sus follow-ups del día'")),
                ('category', models.CharField(choices=[('leads', '📊 Gestión de Leads'), ('followups', '📅 Seguimiento y Recordatorios'), ('payments', '💰 Pagos y Cobranzas'), ('reports', '📈 Reportes y Análisis'), ('inventory', '🏗️ Inventario'), ('notifications', '📧 Notificaciones'), ('maintenance', '🔧 Mantenimiento del Sistema')], help_text='Categoría de la tarea', max_length=50)),
                ('task_name', models.CharField(help_text='Nombre técnico (automático)', max_length=255)),
                ('frequency', models.CharField(choices=[('hourly', 'Cada Hora'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='daily', help_text='¿Con qué frecuencia se ejecuta?', max_length=20)),
                ('hour', models.IntegerField(default=8, help_text='Hora (0-23). Ej: 8 = 8 AM, 14 = 2 PM, 20 = 8 PM')),
                ('minute', models.IntegerField(default=0, help_text='Minuto (0-59)')),
                ('day_of_week', models.CharField(blank=True, choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('0', 'Domingo')], help_text='Para tareas semanales: qué día ejecutar', max_length=10)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Para tareas mensuales: día del mes (1-31)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Activar/Desactivar tarea')),
                ('last_run', models.DateTimeField(blank=True, editable=False, help_text='Última vez que se ejecutó', null=True)),
                ('total_runs', models.IntegerField(default=0, editable=False, help_text='Total de ejecuciones')),
                ('last_result', models.TextField(blank=True, editable=False, help_text='Resultado de última ejecución')),
                ('last_success', models.BooleanField(default=True, editable=False, help_text='¿Última ejecución fue exitosa?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_tasks', to=settings.AUTH_USER_MODEL)),
                ('periodic_task', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Tarea Programada',
                'verbose_name_plural': 'Tareas Programadas',
                'ordering': ['category', 'name'],
            },
        ),
    ]
