# Generated by Django 4.2.10 on 2025-10-16 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lead_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('alternate_phone', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('nurturing', 'Nurturing')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('trade_show', 'Trade Show'), ('partner', 'Partner'), ('other', 'Other')], default='website', max_length=20)),
                ('source_detail', models.CharField(blank=True, max_length=255)),
                ('lead_score', models.IntegerField(default=0, help_text='Lead score 0-100')),
                ('ai_close_probability', models.IntegerField(default=0, help_text='AI-predicted probability of closing (0-100)')),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('conversion_factors', models.JSONField(blank=True, default=dict)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('last_interaction_date', models.DateTimeField(blank=True, null=True)),
                ('interaction_count', models.IntegerField(default=0)),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_currency', models.CharField(default='USD', max_length=3)),
                ('financing', models.BooleanField(default=False)),
                ('down_payment_percentage', models.IntegerField(blank=True, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Property preferences')),
                ('quote_count', models.IntegerField(default=0)),
                ('total_quote_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_quote_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('converted_to_customer', models.BooleanField(default=False)),
                ('customer_id', models.CharField(blank=True, max_length=100)),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
