# Generated by Django 4.2.10 on 2025-10-16 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('leads', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assigned_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company'),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_projects',
            field=models.ManyToManyField(blank=True, related_name='interested_leads', to='projects.project'),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_units',
            field=models.ManyToManyField(blank=True, related_name='interested_leads', to='projects.unit'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'status'], name='leads_lead_company_2d29e3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_number'], name='leads_lead_lead_nu_947903_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='leads_lead_email_f663dc_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='leads_lead_assigne_3f8857_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-lead_score'], name='leads_lead_lead_sc_348deb_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-ai_close_probability'], name='leads_lead_ai_clos_59f05f_idx'),
        ),
    ]
