# Generated by Django 4.2.10 on 2025-10-16 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0002_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='quote',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='projects.project'),
        ),
        migrations.AddField(
            model_name='quote',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='projects.unit'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['company', 'status'], name='quotes_quot_company_45ab47_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number'], name='quotes_quot_quote_n_6770d1_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['lead'], name='quotes_quot_lead_id_9a3985_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['project'], name='quotes_quot_project_e593f4_idx'),
        ),
    ]
